package de.souperman.vars;

import de.souperman.types.PokeType;
import de.souperman.types.Pokemon;
import org.bukkit.Bukkit;

import java.util.ArrayList;

public class Vars {

    public static ArrayList<Pokemon> summonedPokemon;


    public static void initVars() {
        summonedPokemon = new ArrayList<Pokemon>();
    }

    public static void updatePos() {
        for (Pokemon pokemon : summonedPokemon) {
            pokemon.getArmorStand().setRotation(pokemon.getArmorStand().getLocation().getYaw() + 1, pokemon.getArmorStand().getLocation().getPitch());
        }
    }


    public static int getModelData(PokeType type) {
        switch (type) {
            case BULBASAUR:
                return 10001;
            case IVYSAUR:
                return 10002;
            case VENUSAUR:
                return 10003;
            case CHARMANDER:
                return 10004;
            case CHARMELEON:
                return 10005;
            case CHARIZARD:
                return 10006;
            case SQUIRTLE:
                return 10007;
            case WARTORTLE:
                return 10008;
            case BLASTOISE:
                return 10009;
            case CATERPIE:
                return 10010;
            case METAPOD:
                return 10011;
            case BUTTERFREE:
                return 10012;
            case WEEDLE:
                return 10013;
            case KAKUNA:
                return 10014;
            case BEEDRILL:
                return 10015;
            case PIDGEY:
                return 10016;
            case PIDGEOTTO:
                return 10017;
            case PIDGEOT:
                return 10018;
            case RATTATA:
                return 10019;
            case RATICATE:
                return 10020;
            case SPEAROW:
                return 10021;
            case FEAROW:
                return 10022;
            case EKANS:
                return 10023;
            case ARBOK:
                return 10024;
            case PIKACHU:
                return 10025;
            case RAICHU:
                return 10026;
            case SANDSHREW:
                return 10027;
            case SANDSLASH:
                return 10028;
            case NIDORAN_F:
                return 10029;
            case NIDORINA:
                return 10030;
            case NIDOQUEEN:
                return 10031;
            case NIDORAN_M:
                return 10032;
            case NIDORINO:
                return 10033;
            case NIDOKING:
                return 10034;
            case CLEFAIRY:
                return 10035;
            case CLEFABLE:
                return 10036;
            case VULPIX:
                return 10037;
            case NINETALES:
                return 10038;
            case JIGGLYPUFF:
                return 10039;
            case WIGGLYTUFF:
                return 10040;
            case ZUBAT:
                return 10041;
            case GOLBAT:
                return 10042;
            case ODDISH:
                return 10043;
            case GLOOM:
                return 10044;
            case VILEPLUME:
                return 10045;
            case PARAS:
                return 10046;
            case PARASECT:
                return 10047;
            case VENONAT:
                return 10048;
            case VENOMOTH:
                return 10049;
            case DIGLETT:
                return 10050;
            case DUGTRIO:
                return 10051;
            case MEOWTH:
                return 10052;
            case PERSIAN:
                return 10053;
            case PSYDUCK:
                return 10054;
            case GOLDUCK:
                return 10055;
            case MANKEY:
                return 10056;
            case PRIMEAPE:
                return 10057;
            case GROWLITHE:
                return 10058;
            case ARCANINE:
                return 10059;
            case POLIWAG:
                return 10060;
            case POLIWHIRL:
                return 10061;
            case POLIWRATH:
                return 10062;
            case ABRA:
                return 10063;
            case KADABRA:
                return 10064;
            case ALAKAZAM:
                return 10065;
            case MACHOP:
                return 10066;
            case MACHOKE:
                return 10067;
            case MACHAMP:
                return 10068;
            case BELLSPROUT:
                return 10069;
            case WEEPINBELL:
                return 10070;
            case VICTREEBEL:
                return 10071;
            case TENTACOOL:
                return 10072;
            case TENTACRUEL:
                return 10073;
            case GEODUDE:
                return 10074;
            case GRAVELER:
                return 10075;
            case GOLEM:
                return 10076;
            case PONYTA:
                return 10077;
            case RAPIDASH:
                return 10078;
            case SLOWPOKE:
                return 10079;
            case SLOWBRO:
                return 10080;
            case MAGNEMITE:
                return 10081;
            case MAGNETON:
                return 10082;
            case FARFETCHD:
                return 10083;
            case DODUO:
                return 10084;
            case DODRIO:
                return 10085;
            case SEEL:
                return 10086;
            case DEWGONG:
                return 10087;
            case GRIMER:
                return 10088;
            case MUK:
                return 10089;
            case SHELLDER:
                return 10090;
            case CLOYSTER:
                return 10091;
            case GASTLY:
                return 10092;
            case HAUNTER:
                return 10093;
            case GENGAR:
                return 10094;
            case ONIX:
                return 10095;
            case DROWZEE:
                return 10096;
            case HYPNO:
                return 10097;
            case KRABBY:
                return 10098;
            case KINGLER:
                return 10099;
            case VOLTORB:
                return 10100;
            case ELECTRODE:
                return 10101;
            case EXEGGCUTE:
                return 10102;
            case EXEGGUTOR:
                return 10103;
            case CUBONE:
                return 10104;
            case MAROWAK:
                return 10105;
            case HITMONLEE:
                return 10106;
            case HITMONCHAN:
                return 10107;
            case LICKITUNG:
                return 10108;
            case KOFFING:
                return 10109;
            case WEEZING:
                return 10110;
            case RHYHORN:
                return 10111;
            case RHYDON:
                return 10112;
            case CHANSEY:
                return 10113;
            case TANGELA:
                return 10114;
            case KANGASKHAN:
                return 10115;
            case HORSEA:
                return 10116;
            case SEADRA:
                return 10117;
            case GOLDEEN:
                return 10118;
            case SEAKING:
                return 10119;
            case STARYU:
                return 10120;
            case STARMIE:
                return 10121;
            case MRMIME:
                return 10122;
            case SCYTHER:
                return 10123;
            case JYNX:
                return 10124;
            case ELECTABUZZ:
                return 10125;
            case MAGMAR:
                return 10126;
            case PINSIR:
                return 10127;
            case TAUROS:
                return 10128;
            case MAGIKARP:
                return 10129;
            case GYARADOS:
                return 10130;
            case LAPRAS:
                return 10131;
            case DITTO:
                return 10132;
            case EEVEE:
                return 10133;
            case VAPOREON:
                return 10134;
            case JOLTEON:
                return 10135;
            case FLAREON:
                return 10136;
            case PORYGON:
                return 10137;
            case OMANYTE:
                return 10138;
            case OMASTAR:
                return 10139;
            case KABUTO:
                return 10140;
            case KABUTOPS:
                return 10141;
            case AERODACTYL:
                return 10142;
            case SNORLAX:
                return 10143;
            case ARTICUNO:
                return 10144;
            case ZAPDOS:
                return 10145;
            case MOLTRES:
                return 10146;
            case DRATINI:
                return 10147;
            case DRAGONAIR:
                return 10148;
            case DRAGONITE:
                return 10149;
            case MEWTWO:
                return 10150;
            case MEW:
                return 10151;
            default:
                return 0;
        }
    }
}